-- Track processed Stripe events for idempotency.
-- Run this in Supabase SQL editor / migrations.

create table if not exists public.stripe_events (
  id bigint generated by default as identity primary key,
  event_id text not null unique,
  type text,
  created_at timestamptz not null default now()
);

